config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  root 'jobs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :jobs
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :find_job, only: [:show, :edit, :update, :destroy]

  def index
    @jobs = Job.all
  end

  def show
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(jobs_params)

    if @job.save
      redirect_to @job
    else
      redirect_to root_path
    end
  end

  def edit
  end

  def update
    if @job.update(jobs_params)
      redirect_to @job
    else
      render "Edit"
    end
  end

  def destroy
    @job.destroy
      redirect_to root_path
  end

  private

  def jobs_params
    params.require(:job).permit(:title, :description, :company, :url)
  end

  def find_job
    @job = Job.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= simple_form_for @job do |f| %>

 <%= f.input  :title %>
 <%= f.input  :description %>
 <%= f.input  :company %>
 <%= f.input  :url %>
 <%= f.button :submit %>
<% end %>

app/views/jobs/edit.html.erb
<h1> Edit Job Listing </h1>

<%= render 'form' %>

<%= link_to "Back", root_path %>

app/views/jobs/index.html.erb
<h1> Job Board </h1>

<ul class="jobs">
  <% @jobs.each do |job| %>
    <li> <%= job.title %> </li>
    <li> <%= job.company %> </li>
  <% end %>
</ul>


<%= link_to "New Job", new_job_path %>

app/views/jobs/new.html.erb
<h1> New Job Listing </h1>

<%= render 'form' %>

<%= link_to "Back", root_path %>

app/views/jobs/show.html.erb
<h1><%= @job.title %></h1>
<p><%= @job.description %></p>
<p><%= @job.company %></p>
<p><%= @job.url %></p>

<%= link_to "Home", root_path %>
<%= link_to "Edit", edit_job_path(@job) %>
<%= link_to "Delete", job_path(@job), method: :delete, data: { confirm: "Are you sure?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Job Board</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>